### ISSUE TITLE
Status Code, 200

### ISSUE THREAD

**Issue by raymondtam** [brave/wordpress-well-known#1]
I would like to ask if there is any chance to send a 200 instead of 404 status code. Thanks in advance.

Background: I am working on Apple pay with wordpress and stripe, which i have to verify my domain. After spending 9 hours working on htaccess, i have came to your plugin. and got no luck with another hour trying to force it to send back 200.

**Comment by mrose17** [comment]
@raymondtam - sorry for the delay in replying. help me understand why you're getting a 404. presumably there is a particular filename that you need the plugin to support. what is it? thanks!

**Comment by mrose17** [comment]
closed due to lack of reply.
