### ISSUE TITLE
tell Brave publishers to uninstall this plugin as soon as their site is verified

### ISSUE THREAD

**Issue by diracdeltas** [brave/wordpress-well-known#2]
that would greatly limit the security risks associated with installing this (or any) wordpress plugin.

we should warn publishers to uninstall this plugin ASAP wherever this plugin is advertised (in the README, on the publishers site?, etc.)

**Comment by mrose17** [comment]
i've updated the README, as a practical matter the instructions on the publishers site also need to re-iterate this, cf., https://github.com/brave-intl/creators-private-issues/issues/1231
